version: '3'

services:
  legacy_database:
    image: mariadb:10.4-focal
    environment:
      MYSQL_DATABASE: "legacy_db"
      MYSQL_USER: "legacy_usr"
      MYSQL_PASSWORD: "legacy_pwd"
      MYSQL_ROOT_PASSWORD: "legacy_root_pwd"
      MYSQL_ROOT_HOST: "%"

    ports:
      - "3306:3306"
    volumes:
      - ./containers/legacy_database:/docker-entrypoint-initdb.d
      - ./containers/legacy_database/conf:/etc/mysql/conf.d
      - legacy_database_data:/var/lib/mysql

  legacy_app:
    build: containers/legacy_app/
    depends_on:
      - legacy_database
    volumes:
      - ./containers/legacy_app/:/code:ro
    command: 'php /code/app.php'

  greenfield-app:
    build: ./containers/greenfield_app/
    environment:
      APACHE_DOCUMENT_ROOT: '/var/www/html/public'
    volumes:
      - ./containers/greenfield_app:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    command: >
      bash -c "composer install
      && chmod -R 777 vendor
      && apache2-foreground"

  mediator:
    image: node
    user: "node"
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    depends_on:
      - legacy_database
      - legacy_app
      - greenfield-app
    volumes:
      - ./containers/mediator/:/home/node/app
    command: >
      bash -c "npm install
      && chmod -R 777 node_modules
      && node ."
      

volumes:
  debezium_data:
  legacy_database_data: